### ISSUE TITLE
Reports error when refreshing the editor

### ISSUE THREAD

**Issue by zwz** [andrewjk/tiptap-svelte#1]
I tried `tiptap-svelte-examples`.
When you just refresh the browser at, say `http://localhost:3000/basic`,
it reports some `Loading chunk error`.
(You probably have to hit `esc` key quickly after refreshing, so as to stop and see the error)

**Comment by andrewjk** [comment]
Ah yeah, looks like I should have read my own docs more closely. Each editor needs to be created in onMount with checks to make sure it exists in the HTML.

Thanks!
